### ISSUE TITLE
error on xpub wallet with hundreds of txns [ios]

### ISSUE THREAD

**Issue by ncstdc** [BlueWallet/BlueWallet#1057]
I'm using the ios version 5.3.6. I have an xpub wallet I'm watching that has ~700 transactions and getting this popup alert:

<img width="270" alt="2020-05-08 08-33-39-1" src="https://user-images.githubusercontent.com/2712736/81410745-e077cb80-9106-11ea-81fc-1f40e36a9bc4.png">

It does show the correct balance (goes back to 0 after restart) and only two transactions, 546 and 547. There is nothing different about these two transactions compared to the rest. My guess is that this is probably the upper limit in terms of the number of txns. 

Other xpubs with smaller number of transactions load fine. I have tried using the default electrum server as well as my locally hosted with the same error.

**Comment by Overtorment** [comment]
Is that BIP44 wallet?

**Comment by ncstdc** [comment]
yes

**Comment by Overtorment** [comment]
Any chance you can privately share it to i@bluewallet.io?  Ill try to debug

**Comment by ncstdc** [comment]
any luck with it?

**Comment by Overtorment** [comment]
Got the xpub, will debug, on my todo list 👍

**Comment by Overtorment** [comment]
Will post updates to this ticket

**Comment by Overtorment** [comment]
alert fixed in https://github.com/BlueWallet/BlueWallet/pull/1099
balance bug most likely fixed as well. 

I will be doing some more optimizations so BW can handle this many transactions in a single wallet better.

will be out in v5.3.8+
(most likely in 1-2 weeks)

closing ticket for now, pls reopen if something is not right!
