### ISSUE TITLE
Cannot import Electrum wallet into Bluewallet

### ISSUE THREAD

**Issue by sypher9** [BlueWallet/BlueWallet#1088]
Steps:

1. Created standard wallet on Electrum 3.3.8
2. Create new seed
3. Segwit
4. pipe material theme van foster palace float toilet bar surge strong doll (it's a empty wallet, relax)
5. In Bluwallet 5.3.6 for iOS, checked Electrum Server is connecter, did self-test : OK 
4. In Bluewallet, import new wallet. Entered seed. Get error Failed to import. Please make sure that the provided data is valid.

**Comment by Overtorment** [comment]
ok I checked the code and it works like this:
BW unwraps seed and checks if there are any transactions. since there are none and seed format is electrum's - BW skips it just for any case.
if you fund it with a lil bit of balance it should import ok, I tested this scenario when I was adding electrum seed support

**Comment by ricardoreis** [comment]
Ideally, BlueWallet would import even if it does not have any transactions on Electrum Wallet.

**Comment by artk47** [comment]
I believe it is a case to re-open:
- I used electrum as a co-signer and coordinator for multisig vault with 2 x bluewallets, so when I was testing recovery to bluewallet desktop, I was not able to recover all vault keys, because Electrum's one was obviously with zero balance.

**Comment by artk47** [comment]
> Ideally, BlueWallet would import even if it does not have any transactions on Electrum Wallet.

Unfortunately - No. Since there is no way to convert electrum seeds to bip39 and vice versa. So i haven't learned in details, but i hope that BW only provide the option to sweep the balance to new bip 39 seed after importing electrum seed, bc it does make no sense for BW to give further life for electrum seeds - it is dangerous for user funds.
