### ISSUE TITLE
opt-out of icloud

### ISSUE THREAD

**Issue by khayto** [BlueWallet/BlueWallet#1108]
would be nice if it was possible to do that. currently all private keys are sent from my device to my icloud account, cant find bluewallet in the list of apps installed on my device to disable it manually.

**Comment by ncoelho** [comment]
Hi @khayto can you send us more info, can you see any of BlueWallet data on iCloud?

If the app doesn't appear on the iCloud list is because it is not being backed up there. If you try to import your iCloud backup, you won't get any of your wallets back, this data shouldn't be sent to iCloud. There can be an error, but I doubt no one have seen that before.

**Comment by ncoelho** [comment]
If no doubts exist, I'm closing this issue. Feel free to comment/reopen.
