### ISSUE TITLE
CPFP

### ISSUE THREAD

**Issue by Overtorment** [BlueWallet/BlueWallet#118]

**Comment by pajasevi** [comment]
So, I guess this is not possible right now only because of `if (unspent.confirmations < 2) {` in `signer.js`. Is there any reason, for not handling unconfirmed UTXOs and throwing errors instead? Just asking.

**Comment by pajasevi** [comment]
ping @Overtorment

**Comment by pajasevi** [comment]
Ok, I understand the issue with unwanted double-spending or more like one tx canceling the other. But CPFP is a feature of the protocol, it should not be a direct feature of the wallet.

The problem is that you can never know if the utxo wasn't spent until it is confirmed in a block. Even if you have your own node with tx mempool as a backend.

So I would still allow users to spend unconfirmed utxos but would display a warning that informs the user of this and its downsides. Wallet would need to hold a cache of unconfirmed "used" utxos to minimalize any errors.

**Comment by Overtorment** [comment]
You are talking about good UTXO management.

>> But CPFP is a feature of the protocol, it should not be a direct feature of the wallet.

Not sure. Do you have examples of good wallets that hide CPFP completely from user and make it part of user flow? And it works flawlessly..? To my understanding, CPFP should be used only in cases when user wants to speed up confirmation, and it requires some additional input from user, and additional actions from wallet. For example, wallet needs to recalculate fee of sum (parent tx + new child tx) and make sure it is higher than fee of single parent tx (sat/b ofcourse). And not only that, that fee should be tempting for miners to include both txs in block, so fee should be targeted to some specific value (from fee estimation service). Say, we want both txs (child + parent) to be 40 sat/b, because single parent tx is only 1 sat/b, and that is not tempting enough for miners. So we explain and show user his options, that he can choose new fee for combination of (parent tx + child tx).
So the way I see it, CPFP should be a feature to perform on incoming transactions user really-really wants to speed-up.

I might be wrong tho. Good example from other wallets would be helpful.

@ncoelho you input on this matter would be invaluable, UX wise.
