### ISSUE TITLE
Overpayed invoice results in lost funds

### ISSUE THREAD

**Issue by PARSA5M** [BlueWallet/BlueWallet#1492]
Allowing payments of more than 2x over invoice is out of spec with [BOLT04](https://github.com/lightningnetwork/lightning-rfc/blob/master/04-onion-routing.md#failure-messages).
`if the amount paid is more than twice the amount expected:

    SHOULD fail the HTLC.
    SHOULD return an incorrect_or_unknown_payment_details error. `

**Comment by Overtorment** [comment]
More details would be nice

**Comment by PARSA5M** [comment]
1. I created an invoice via BlueWallet for 5sat. 
2. Than i payed the invoice via PhoenixWallet using their "send all" feature.
3. BlueWallet receved +5sat.

My intention was to empty my PhoenixWallet. The 5sat I put in as a "placeholder" because Blue Wallet cant generate an invoice without a specific amount. I was too lazy to put in the specific amount that was left in my Phoenix Wallet.

https://imgur.com/a/orDvFBc

**Comment by Overtorment** [comment]
so the problem is on phoenixwallet side. on bw side, its like, "okay, I see invoice for 5 sats. it has flag 'settled' so here are your 5 sats, thank you very much".

also, I don't think any implementation enforces that rule about 2x, yet. its more like sanity check for the user.
you can send any amount via cli via a specific route : 

![image](https://user-images.githubusercontent.com/1913337/90769199-c180fc00-e2e7-11ea-9f0b-af6be7a3fdcf.png)

**Comment by PARSA5M** [comment]
I am lost without gui ... cli or specific route? I am just using apps on my phone ;)

Are the missing funds still available without being displayed or are they lost?

Two more things I want to let you know:

- The pushnotification from BlueWallet if you receive funds shows the full amount sent ... but in the app you are just credited the specific invoice amount.

- Breeze Wallet credits the full amont sent

**Comment by Overtorment** [comment]
extra funds sit on receiver's node, its just takes some manual labour to extract them.

easier to fix push notification's text

**Comment by Overtorment** [comment]
https://github.com/BlueWallet/GroundControl/issues/11
