### ISSUE TITLE
tests should run with browser env considering browserified modules are used on react-native instead of node crypto module

### ISSUE THREAD

**Issue by vesparny** [BlueWallet/BlueWallet#1730]
Hi, considering the app uses rn-nodeify to force modules to respect the "browser" field for some key dependencies, shouldn't tests run using this jest resolver?

![image](https://user-images.githubusercontent.com/82070/92633561-3afe7f80-f2d3-11ea-8489-e711bb63d0b5.png)

https://jestjs.io/docs/en/configuration

**Comment by Overtorment** [comment]
I dont know, Im not very good with this topic. Should they?
Tests do run as is okay.

**Comment by vesparny** [comment]
I think they should.
Tests are executed in a node environment (which uses the crypto module), while in react-native, that module is not available and BlueWallet relies on rn-nodeify to forse all packages to use the corresponding browserify version.

Imagine a bug arises in a browserified module which breaks any of the functionalities (signing or address generation).
This bug wouldn't be spotted while running the tests because in that case the node crypto module would be used instead of the browserified version.

I am not sure I am 100% right because maybe you already cover this situation using some config which I missed, but I though a heads-up was well worth 👍

**Comment by Overtorment** [comment]
first, I dont think we can make cli environment use rn modules, as they typically have android (java) and ios (objc & swift) code, so that just wont fly. to be precise, only 1 module is important here - `react-native-randombytes`. all other crypto operations like signing is pure javascript and is identical on cli & RN.
second, we have extensive end-to-end tests which test both signing and entropy generator in real life build app.

**Comment by vesparny** [comment]
Ok
