### ISSUE TITLE
Integrating Blue wallet with ios app.

### ISSUE THREAD

**Issue by Naushad-chicmic** [BlueWallet/BlueWallet#2053]
Hello
We have to integrate blue wallet in an ios app for making trasaction using bitcoin.
Please guide us if there are web resources containing api endpoint or sdk etc.

Thanks and Regards

**Comment by Overtorment** [comment]
can you be a bit more specific

**Comment by Naushad-chicmic** [comment]
Our app has purchasable assets which can be buy by using bitcoin. We want our user to redirect on bluewallet to sign the transaction. how can we achieve that ?

**Comment by Overtorment** [comment]
the easiest way is to construct a deeplink in your app and open it: 

https://github.com/bitcoin/bips/blob/master/bip-0021.mediawiki
https://github.com/BlueWallet/BlueWallet/wiki/Deeplinking

**Comment by singhdavinder** [comment]
@Overtorment

**Comment by singhdavinder** [comment]
@Overtorment 
The actual scenario is we want to integrate blue wallet in ios game, and some digital assets have price in satoshi. So we are looking forward to use BlueWallet for same. But unable to figure out the best way for integration. Your suggested solution(using Deeplink URL schemes) seems good to me but how can we listen payment response back to our host game? i.e success, fail. Because we have some other operation to perform according to transaction result.
Looking forward for your reply.
Thanks

**Comment by Overtorment** [comment]
well you need to have some kind of backend that will issue invoices, and then check if invoice is paid, and notifying your app
