### ISSUE TITLE
Switch to 12 word mnemonics by default?

### ISSUE THREAD

**Issue by Overtorment** [BlueWallet/BlueWallet#2122]

**Comment by vesparny** [comment]
why?

**Comment by ncoelho** [comment]
> why?

It is easier to backup and provides the same security.

**Comment by tanx** [comment]
> It is easier to backup and provides the same security.

Well a 12 word seed only provides 128 bits of entropy. According to bip32 265 bits are advised:
https://github.com/bitcoin/bips/blob/master/bip-0032.mediawiki#Master_key_generation

Curious where you got the info about the same security?

**Comment by ncoelho** [comment]
> > It is easier to backup and provides the same security.
> 
> Well a 12 word seed only provides 128 bits of entropy. According to bip32 265 bits are advised:
> https://github.com/bitcoin/bips/blob/master/bip-0032.mediawiki#Master_key_generation
> 
> Curious where you got the info about the same security?

Essentially 128 bits is consider strong enough and it is the level of security that bitcoin core uses. So we thought that saving everyone's time to write 12 words instead of 24 is a perfectly ok change to make, specially in the context of a hot wallet and as well, preparing for the release of the multisig wallet where it makes a huge difference to backup 24 words vs 12.

For reference
https://bitcoin.stackexchange.com/questions/72612/bip32-recommends-a-256-bit-seed-why-do-most-bitcoin-wallets-only-use-a-128-bit/75588#75588

**Comment by tanx** [comment]
Gotcha thanks
