### ISSUE TITLE
Custom Derivation Paths when importing seed words with "Advanced Mode" on (200k Sat Bounty)

### ISSUE THREAD

**Issue by godSaysHODL** [BlueWallet/BlueWallet#2240]
![custom derivation path](https://user-images.githubusercontent.com/14336691/100718134-d30a8300-336f-11eb-9996-5ccecd4ba8c9.png)

**Comment by jaonoctus** [comment]
WIP

https://github.com/jaonoctus/BlueWallet/tree/feature/bip39-advanced-mode-import-screen

**Comment by jaonoctus** [comment]
I really like the Electrum implementation, with autocompletion. Helps a lot, especially for those who back up the seed in metal wallets and only write the first 4 letters of each word.

@ncoelho wdyt?

![image](https://user-images.githubusercontent.com/7918067/120506942-c5749b00-c39c-11eb-8507-6f99ae0dded1.png)

**Comment by ncoelho** [comment]
That, but with a usable keyboard :)

https://github.com/BlueWallet/BlueWallet/issues/3184#issuecomment-847983288

**Comment by godSaysHODL** [comment]
@limpbrains make sure you slide into my DMs on twitter and send me 200k request  🤝

Great job man

twitter.com/godsayshodl

**Comment by jimbojw** [comment]
Is this available on iOS? I only see a textarea for the seed phrase, not a custom derivation path: ![8F329D58-9175-497E-9807-39D3936745AC](https://user-images.githubusercontent.com/71617/160287875-aa9f8eb5-3e11-48d8-9ab4-293c3677e659.jpeg)

BlueWallet ver 6.2.17 (build 1643409602 master)

**Comment by limpbrains** [comment]
Enable advanced mode in Settings

> Is this available on iOS? I only see a textarea for the seed phrase, not a custom derivation path: ![8F329D58-9175-497E-9807-39D3936745AC](https://user-images.githubusercontent.com/71617/160287875-aa9f8eb5-3e11-48d8-9ab4-293c3677e659.jpeg)
> 
> 
> 
> BlueWallet ver 6.2.17 (build 1643409602 master)
> 
> 
> 
> 
> 
>

**Comment by jimbojw** [comment]
Thanks. Turns out that after you enter the seed material, it searches common derivation paths and allows you to specify one (if you hammer the ‘Use custom’ buttons quickly enough).


Unfortunately, the derivation path of the wallet I was trying to import (`m/0’`) is not allowed by BlueWallet. It fails with just the text “wrong derivation path”. It does this irrespective of whether Advanced mode is enabled or not.

![3E0C37A0-D05A-45EA-AB7E-5CD7A1E3025C](https://user-images.githubusercontent.com/71617/160304639-f6f8459a-2599-4d33-b860-fd8636338e51.jpeg)

But don’t worry about it. I’ve given up importing this wallet into BlueWallet.

**Comment by limpbrains** [comment]
@jimbojw 
`’` and `'` are different characters, that is why you are having this error. To enter `'` on iOS you need to long press on `’` and it will allow you to choose different character

**Comment by jimbojw** [comment]
Like I said, I gave up.

Other wallets treat `'` the same as `\`` in derivation paths. I’ve never had this problem anywhere other than BlueWallet.

You could help users by explaining why the derivation path was unacceptable. Tell them the apostrophe is an unrecognized character. “Did you mean to use a backtick (`\``)?” or something.
