### ISSUE TITLE
No transaction history after importing zpub key

### ISSUE THREAD

**Issue by ascisco** [BlueWallet/BlueWallet#2462]
Using the latest version of BlueWallet and Android on a Google Pixel 1. 

I have BlueWallet setup to connect to my electrum server, the network menu displays "connected" (in green) and shows the TOR address of my server. 

I tried importing a zpub key of mine that was originally created in Electrum wallet. After importing, BlueWallet hangs for a while but eventually imports the wallet and displays the balance. However it does not show any transaction history, even when sending a new transaction to the wallet it does not show in the transaction history.

I also tried importing the seed phrase from the same wallet and it still did not show any transaction history.

**Comment by Overtorment** [comment]
have you tries pull-to-refresh? initial import only fetches balances because its faster, and then it displays a message "latest transaction: pull to refresh" :
![image](https://user-images.githubusercontent.com/1913337/103651700-e9e95a00-4f59-11eb-8597-4d610dba2eff.png)


if you still cant get your transactions list, the problem might be a tricky transaction bluewallet chokes on and i would need to debug this.
could you please send your xpub to i@bluewallet.io

**Comment by ascisco** [comment]
Yup I tried to refresh it many times, it just has the spinning wheel for a while and never loads any of the 3 transactions the wallet has.

**Comment by Overtorment** [comment]
is it still happening?

**Comment by ascisco** [comment]
> is it still happening?

Yes this works properly now.
