### ISSUE TITLE
Bug: when connected to custom Lndhub, create new ln wallet -> backup screen doesnt include this custom server

### ISSUE THREAD

**Issue by Overtorment** [BlueWallet/BlueWallet#2493]

**Comment by godSaysHODL** [comment]
I actually really like this issue because it gives me one layer of clipboard privacy if another app is monitoring clipboard, they wont know my home server 🤷‍♂️

**Comment by Overtorment** [comment]
yeah but soon your home server will be onion, right? so no worries

**Comment by godSaysHODL** [comment]
> yeah but soon your home server will be onion, right? so no worries

What I meant was that if another app was to steal the recovery url alone from clipboard data when you are backing it up....
without any server info then they cannot steal funds (if you run your own lndhub, at least)

clipboard theft of:
account(1):password(2) = no funds lost unless they know your server also.

vs

account(1);password(2)@serverinfo = funds potentially stolen via clipboard

I only think like this because we found out from apple's IOS14 features, that Reddit, instagram, tiktok, and others were stealing clipboard data from all apps and datamining that

**Comment by Overtorment** [comment]
yes, but at least on ios they cant steal it right away, you have to switch
to the app for it to get some cpu time so it can read clipboard and steal
it.
not sure how it works on android tho.
