### ISSUE TITLE
Receive, allow to reuse an old address

### ISSUE THREAD

**Issue by Sipke82** [BlueWallet/BlueWallet#2727]
On the receive screen, add an option reuse a old address. Perhaps show the coin control screen. 

That way users can make future transactions cheaper, by limiting the amount of inputs. 

Could be useful for stacking small amounts of sats and later sending a larger amount.

**Comment by limpbrains** [comment]
If you receive 2 payments to the same address, you will have 2 inputs. Reusing addresses doesn't make your future transaction cheaper.

Something similar is WIP here #990

**Comment by mcsaeid** [comment]
But it would be good to be able to generate and see addresses within the wallet rather than receiving just one (which has to be used in order for the wallet to give you a new one). What if you want to receive three separate payments? Is there a workaround?

I think I saw you guys working on a similar thing, but I am not sure.

**Comment by limpbrains** [comment]
Closing because it duplicates #990
