### ISSUE TITLE
Add list of all fiat currencies

### ISSUE THREAD

**Issue by wallclockbuilder** [BlueWallet/BlueWallet#2750]
Anybody from the world's 195 countries should be able see the price of bitcoin in their mother fiat. 
BlueWallet currently covers only 36 fiat currencies.

**Comment by marcosrdz** [comment]
The reason who don't have every fiat is because the exchange price source we utilize does not have all of them. We manually verify their availability and act accordingly. We recently added the ability to obtain the exchange price from alternative sources but these have to be manually added. If you have a fiat unit you'd like to see in BlueWallet please go ahead and list them, or send a pull request, and we will gladly add them.

**Comment by wallclockbuilder** [comment]
I'm happy to do the manual verification necessary for all of them. Perhaps you can review my code when I submit a PR?

**Comment by marcosrdz** [comment]
Sounds good

**Comment by wallclockbuilder** [comment]
Please assign it to me so it shows up on my dashboard.

**Comment by pointbiz** [comment]
Can you please add ANG (Antillean Guilder)?

Or point me to the file that needs updating for a PR.

**Comment by pointbiz** [comment]
I found the file here
https://github.com/BlueWallet/BlueWallet/blob/master/models/fiatUnit.js

I sent a request to Yadio to add ANG. Hopefully, they add it.

If not I'm thinking about a PR that would help several Caribbean fiat currencies that have a fixed exchange rate to USD.

A new source type called “FixedRate” could be added to the enum. Then for rateKey USD can be used and a new variable in the object to express the multiplication factor. In the case of ANG that's 1.79.

**Comment by pointbiz** [comment]
I created a pull request here
https://github.com/BlueWallet/BlueWallet/pull/2850
to add support for USD pegged currencies. Specifically, ANG and AWG.

I found a more straightforward implementation by adding a new member "fixedRate" to the "fiatUnit" class.
