### ISSUE TITLE
Implementation of AOPP

### ISSUE THREAD

**Issue by 21isenough** [BlueWallet/BlueWallet#2861]
Just two days ago, "message signing" was merged and is now available to BlueWallet users. This is a lovely feature but at the same time rather cumbersome with all the "copy and pasting" between applications.

There is a new protocol that specifies the transmission of signed messages via a URI scheme:
https://gitlab.com/aopp/address-ownership-proof-protocol

Would be great if this could find it's way into BlueWallet as it removes a lot of friction for users and provides a smooth experience.

**Comment by Overtorment** [comment]
acknowledged. will look into that

**Comment by Overtorment** [comment]
is there a playground? some webpage that would request address ownership, that I can use to debug AOPP implementation?

PS. https://vasp.com doesn't work

**Comment by Overtorment** [comment]
also, starign at https://aopp.group/#wallets

was AOPP implemented in any of those?

![image](https://user-images.githubusercontent.com/1913337/112732376-860b7780-8f31-11eb-9f04-11a9ec46f200.png)

**Comment by 21isenough** [comment]
No, you'd be the first in production :smile:  There is a fork of Electrum that has implemented it and I just tinkered around with the basic structure for BlueWallet:
https://github.com/pocketbitcoin/BlueWallet/tree/aopp-implementation

**Comment by 21isenough** [comment]
> is there a playground?
Yes, there is one here: https://demo.aopp.group/

**Comment by lclc** [comment]
The Electrum fork will be made public in the next ~24 hours.
The other listed wallets are working on it or have it on their roadmap. 

We didn't talk about AOPP publicly yet actually (outside of this issue).


> > is there a playground?
> 
> Yes, there is one here: https://demo.aopp.group/

Please don't use that as a playground. I'm currently setting up a new one at https://testing.aopp.group (might also take some time as I need some input from a colleague and it's Sunday :)).

**Comment by lclc** [comment]
The Electrum fork is now public: https://gitlab.com/aopp/electrum
The demo-video showcases it here: https://www.youtube.com/watch?v=heP-ufUke-g

Playground (fake-exchange withdrawal): https://testing.aopp.group/

Here you can see when your address has been registered (username / password: admin / admin):
https://testing.21analytics.ch/aopp

The logs of the docker container running on the server (to debug if needed) is available here: http://testing.21analytics.ch:8888/container/1a896994c836

**Comment by Overtorment** [comment]
i think this is a pretty cool use-case for sign/verify.
@limpbrains what do you think?

**Comment by limpbrains** [comment]
After watching a demo, I think it can bring great value, let's do it

**Comment by limpbrains** [comment]
@21isenough @lclc 

Some progress here #2915

It works correctly for Legacy addresses, but not for segwit. Server returns error 400. Probably it can't verify signatures for segwit addresses, because there are 2 different ways for doing it. Electrum and Trezor. More details here https://github.com/bitcoinjs/bitcoinjs-message/pull/29

PS I think adding optional `address` parameter could be useful.

**Comment by lclc** [comment]
That was fast! :)

I just had a look at the logs of testing.21analytics.ch, but there isn't much there. I guess you used demo.aopp.group ?
Please use https://testing.aopp.group/ instead. Then you have the logs publicly accessible here http://testing.21analytics.ch:8888. 


I've always used wrapped SegWit addresses for demoing, but some of my colleagues used bech32 testing the implementation and testing.  It's a public holiday here, but some smarter people than I, who are also involved in AOPP, will provide more input latest by tomorrow.


> PS I think adding optional address parameter could be useful.

What do you mean by this?

**Comment by limpbrains** [comment]
> > PS I think adding optional address parameter could be useful.
> 
> What do you mean by this?

I mean if vasp wants to check ownership of the specific address. I've read a note in FAQ regarding hardware wallets, but still.

For example, vasp knows user address. Then it can authenticate the user by asking him to sign a message.

**Comment by lclc** [comment]
If the VASP has your address already shouldn't it have ownership proof for it already too?

The note in the FAQ comes from Shift Crypto (Bitbox). I also fear that if we leave the option to the VASP that they will ignore it.

**Comment by limpbrains** [comment]
It can be used for:
1. 2fa
- VASP: We see that you are trying to withdraw a lot of money. We also know that address A belongs to you. Can you please sign this message with it, so that we can be sure that it is you?
- User: Here you go
- VASP withdrawing the funds

2. Authorization
Mining pool which don't want to store any personal data for their users, besides address where to send funds to. At first, you can signup with your custom address and then signin 

Probably not worth it to implement until there is no real service that needs it

**Comment by lclc** [comment]
Thanks for the ideas.

1. Since nobody prevents me from signing with someone else's name it probably wouldn't really add any value as 2FA ?

2. This sounds interesting. I don't know enough about mining to evaluate the use-case.

Can I ask you to open up issues for the two ideas in the GitLab repo where the specs are (https://gitlab.com/aopp/address-ownership-proof-protocol/-/issues/)? 

But yes, it will probably be for a later version. First, we'd like to keep it as simple as possible, to make get enough adoption :)

**Comment by dspicher** [comment]
> @21isenough @lclc
> 
> Some progress here #2915
> 
> It works correctly for Legacy addresses, but not for segwit. Server returns error 400. Probably it can't verify signatures for segwit addresses, because there are 2 different ways for doing it. Electrum and Trezor. More details here [bitcoinjs/bitcoinjs-message#29](https://github.com/bitcoinjs/bitcoinjs-message/pull/29)
> 
> PS I think adding optional `address` parameter could be useful.

Thanks for the report @limpbrains. We're aware of the issue and will have fixed our backend to recognize both ways by the end of the week.

**Comment by 21isenough** [comment]
Awesome job, @limpbrains!! Look how very smooth a sign up flow with a VASP can be made :partying_face: (AOPP VASP demo).

https://user-images.githubusercontent.com/39227503/113781661-4dd61700-9731-11eb-849e-86e2ecf13a74.mp4

**Comment by lclc** [comment]
Great job, guys!

Which logo-version can I add to the website?
