### ISSUE TITLE
Support for bech32m send

### ISSUE THREAD

**Issue by ncoelho** [BlueWallet/BlueWallet#3394]
For bech32m support we should start with the ability to send. The ability to receive will be covered later with another issue.

**Comment by Overtorment** [comment]
i thought we automatically support it?

@junderw can you shed some light on this?
this is what we use for address validation btw

```js
  isAddressValid(address) {
    try {
      bitcoin.address.toOutputScript(address);
      return true;
    } catch (e) {
      return false;
    }
  }
```

**Comment by junderw** [comment]
Are you using github master?

If not you can't use it yet.

**Comment by junderw** [comment]
Please keep this in mind: https://github.com/bitcoinjs/bitcoinjs-lib/issues/1750

What this means:

1. Any witness version >v1 will NOT throw an error, and will generate an output script with the embedded data and segwit version. (This is expected behavior of the segwit standard, and it is recommended that wallets to parse addresses for future segwit versions)
2. HOWEVER, if a user generates a v2 ~ v16 segwit address and sends to it, any miner can spend that output!
3. This means that "this is a valid address that produces a valid output which we return" and "this is a safe output" are NO LONGER GUARANTEED TO BE LINKED. So wallets should add extra validation, and warn the user if they try to use an address with v2 ~ v16.
4. The above issue is saying that we currently treat v1 also as "I don't know this version, but I will generate the output script anyways" type... to resolve the above issue, we must throw an error when the witness program is not 32 byte length. (since v1 is defined, we know !== 32 length is an error and must throw.

Extra logic should be added to BlueWallet to accomodate.

**Comment by junderw** [comment]
Re: why we decode v2 ~ v16 segwit addresses when their outputs are spendable by miners.

https://github.com/bitcoin/bips/blob/edffe529056f6dfd33d8f716fb871467c3c09263/bip-0350.mediawiki#Addresses_for_segregated_witness_outputs

> To decode an address, client software should either decode with both a Bech32 and a Bech32m decoder[2], or use a decoder that supports both simultaneously. In both cases, the address decoder has to verify that the encoding matches what is expected for the decoded witness version (Bech32 for version 0, Bech32m for others).

**Comment by junderw** [comment]
I remember a lot of people talking about this nuance and saying "well, if wallets would just do it this way, they would all support sending to taproot or whatever v2 will be etc. without needing to release a new version of software!!! yay!!"

But that is a developer's thinking, and I can just imagine someone being tricked into sending into a segwit v16 address...

So wallets that break the standard and reject versions they don't know (or at least throw a big warning saying "I can decode this, but you might be sending money into a black hole, are you sure!?!?!?")

**Comment by Overtorment** [comment]
i gave it a little thought and decided that its easier to _reject_ addresses with an unknown segwit version.
i created a PR for that here: https://github.com/BlueWallet/BlueWallet/pull/4268
