### ISSUE TITLE
should add user self define amount and expire time when create Invoice.

### ISSUE THREAD

**Issue by oday0311** [BlueWallet/BlueWallet#358]
LND support 
Please make a donation of any amount , and multi time ?
not Expire time or very big Expire time , 

Blue wallet please add support to this feature. ( user can define the expire time of invoice, and the 0 amount)

otherwise, currently blue wallet only support one-to-one payment, and

**Comment by davidapple** [comment]
Every invoice I've sent has expired before the recipient has had time to pay. Please develop immortal, perpetual, everlasting, never-ending invoices.

**Comment by davidapple** [comment]
Please add this to your roadmap.

I'm not able to use Blue Wallet with my friends in different time zones because invoices expire after just a few minutes. It impracticable to expect everyone to have constant access to their Blue Wallets and pay immediately after receiving invoices. People have to sleep and some people are not comfortable carrying smartphones around with bitcoin apps on them for security reasons. It's a huge use case that Blue Wallet is not currently able to facilitate.

Invoices in the real world have payment terms of 7 or 30 days. Why does Blue Wallet have payment terms of 1 hour?

**Comment by ncoelho** [comment]
Added to the roadmap

**Comment by davidapple** [comment]
Perhaps the design should be a simple drop down menu when the user creates an invoice.

Expire invoice after:
1 hour
12 hours
1 day
7 days
1 month
6 months
1 year

**Comment by oday0311** [comment]
wa,,, only using 666 to praise your team....

**Comment by davidapple** [comment]
Do you have any updated on expiring invoices?
