### ISSUE TITLE
Doesn't support BIP38 SegWit wallets

### ISSUE THREAD

**Issue by ValleZ** [BlueWallet/BlueWallet#4156]
Try to import this BIP38 wallet:
​6PYRFsPKrpyk2qdz4Sm4QSrWzMKpNy6LCoCZJ8z5gtmubk3kG9P6Vft9dz
password 12345

It fails because it's a SegWit address.
Decrypted key is KxQdS9UeCDv8stcfADiMMttVXgNvFAnwhrGhseDMjUHXW2Unxaoz. Address ​bc1qkjntlwk9m99xj6j2tdpgzefu6uku0k88k94q6a

(also any wallet import fail if you are in airplane mode but it's a different issue)

**Comment by Overtorment** [comment]
it probably fails because the password is incorrect

![image](https://user-images.githubusercontent.com/1913337/140340681-5768590b-fc72-40cc-97b1-bfa172758fc5.png)

**Comment by ValleZ** [comment]
The password is correct, the encrypted wallet conforms BIP38.

**Comment by ValleZ** [comment]
You can try Mycelium wallet. (or Android Paper Wallet)

**Comment by ValleZ** [comment]
Do you have an example of a SegWit wallet encrypted with BIP38 which is accepted by the BlueWallet?

**Comment by Overtorment** [comment]
bitcoinjs/bip38 lib also thinks this is invalid:

https://runkit.com/overtorment/606345c119ab5a0013036416

![image](https://user-images.githubusercontent.com/1913337/140421484-f5b90ea6-fa99-40a7-b126-91eb15ddb436.png)

(this lib usually throws on incorrect passwords)

and bitaddress.org thinks its invalid. id say its invalid.
but if you're 146% sure its valid, I can raise an issue in bip38 repo so they could take a closer look.


PS. we have some test vectors for bip38 wallets and bech32 single-address wallets, but not bip38-bech32-single-address. https://github.com/BlueWallet/BlueWallet/blob/master/tests/unit/bip38.test.js  https://github.com/BlueWallet/BlueWallet/blob/master/tests/unit/hd-segwit-bech32-wallet.test.js

**Comment by junderw** [comment]
it's invalid. BIP38 doesn't support segwit.

**Comment by ValleZ** [comment]
It obviously does. The example key is encoded bech32 address.

**Comment by junderw** [comment]
I now understand the issue.

OP has created an Android app that uses the bech32 segwit address for hash verification of decryption. This is not in the BIP38 spec, so any bip38 library will fail password verification unless it also compares the bech32 hash, then passes if either or passes.

The path forward should be:

1. OP's app should only generate encrypted keys using the legacy base58 address for hash verification.
2. OP's app should decrypt keys using either base58 OR bech32. Since its users will have keys using bech32, and the wallet generating the key should always be able to decrypt the key.
3. Once 1 and 2 are fixed. Password verification will pass, BUT BlueWallet will only generate a P2PKH base58 address... so BlueWallet should decide whether to use that decrypted private key to also derive bech32 (and maybe wrapped segwit?) and check them as well. This will allow for people who use the decrypted private keys to generate segwit addresses to recover using BlueWallet.

**Comment by junderw** [comment]
Reopened to get a decision on (3) in the list above.

Or does BW already generate multiple addresses after decrypting bip38?

**Comment by Overtorment** [comment]
thanks @junderw!
BW converts bip38 to wif, and then we probe each address type for transactions ( https://github.com/BlueWallet/BlueWallet/blob/0c6d613f5a870b9eaabb79a7516b2c8d85d344e7/class/wallet-import.js#L270 ), so bech32 address should be detected okay (if it was ever used). there was some bech32 online paper wallet generator around, which I tested this against (no bip38 tho).

cc @limpbrains

**Comment by Overtorment** [comment]
is there anything actionable here? closing if not
