### ISSUE TITLE
Cannot send anything at 1sat/byte

### ISSUE THREAD

**Issue by Transisto** [BlueWallet/BlueWallet#4352]
to reproduce

Select a single UTXO with coin control

Select default fee of 1 sat per byte.

Wallet will produce a transaction of 113 Bytes with a total fee of 112 Sat making it below the minimum relay fee of 1sat/byte.

I might have posted a few similar issue or comments, This has been happening to me regularly.

**Comment by Transisto** [comment]
At least if we could select 1.1 sat that would fix it up without doubling the transaction cost.

**Comment by Overtorment** [comment]
I assume its also a tx with only single output? no change?

and which type, BIP84 (native segwit) ?

**Comment by sebastian13** [comment]
Same. Error message:

_min relay fee not met, 112 < 113_

- type: HD SegWit
- Transaction with single input + single output, no change
- 1 sat/vByte fee

**Comment by Transisto** [comment]
Yes, this

Was segwit to legacy address,

Transferring a single utxo

**Comment by Transisto** [comment]
Same thing happening with latest version.

![Screenshot_20220131-011035_BlueWallet](https://user-images.githubusercontent.com/388716/151747590-ab1aea41-f2fe-48b3-9306-a619d54d9e46.jpg)

1 input 2 output,
1 sat per bytes.

**Comment by Transisto** [comment]
This is so ridiculous, How long can it take to make the lowest fee be 1.1 sat/byte?

**Comment by Transisto** [comment]
This happens with any regular transaction sending to a BECH32 P2WSH address like bc1qtmcfj7lvgjp866w8lytdpap82u7eege58jy52hp4ctk0hsncegyqel8prp

**Comment by landabaso** [comment]
@Overtorment, I'm wondering what if the lengthy address is on the changeAddress. changeAddress is not being compensated (+3 bytes).
It looks like the {script: {length}} trick for coinselect cannot be applied to changeAddresses. It could be added to one of the targets but the thing is we don't event know if changeAddress will be needed. It's tricky.

**Comment by Transisto** [comment]
@landabaso from what I read the +3 is not what's doing the trick but actually looking at the length of the address.

What would be IMO simple is to aim for 1.1 sat/bytes since so many wallets make it easier to select the minimum relay fee and integers the mempool tend to get filled at exactly 1.00sat/bytes.

**Comment by landabaso** [comment]
Thanks @Overtorment. I think I didn't explain myself clearly (either that or there's something I don't undersand).

This is how coinselect counts bytes for the outputs:

https://github.com/bitcoinjs/coinselect/blob/master/utils.js
```

function outputBytes (output) {
  return TX_OUTPUT_BASE + (output.script ? output.script.length : TX_OUTPUT_PUBKEYHASH)
}
```
It assumes P2PKH unless `{script:{length}}` is passed. That's why you pass: `bitcoin.address.toOutputScript(t.address).length` which makes sense because it correctly gets the size of the output of all the different types of addresses.

The thing is the final tx will also include the output for change (when needed).

If change is needed, coinselect adds `BLANK_OUTPUT` bytes to the tx size (line 43 in [utils.js](https://github.com/bitcoinjs/coinselect/blob/master/utils.js#L43)) to compute the final fee.

`BLANK_OUTPUT` is always calculated assuming a P2PKH output:

`var BLANK_OUTPUT = outputBytes({})`

My point was that coinselect never knows what kind of change address was used for change (P2WKPH, P2SH-P2WPKH or P2PKH). It will always assume P2PKH because there is no way to pass a script structure for the change address.

**Comment by landabaso** [comment]
In case it helps. The test below fails on my project because the actual fee rate is in fact below 1.
I believe we are dealing with the same issue.

I'm also using coinselect and also applied the same `{script:{length}}` trick similarly as you guys:

```
    if (purpose === LEGACY) {
      //Don't do anything here
    } else if (purpose === NESTED_SEGWIT) {
      utxo.script = { length: 50 };
    } else if (purpose === NATIVE_SEGWIT) {
      utxo.script = { length: 27 };
    } else {
      throw new Error(
        'coinselect does ONLY work with p2wpkh, p2sh-p2wpkh or p2wpkh'
      );
    }
```

It's a test that sends a Segwit utxo to a Legacy address. Since it's sending to a Legacy address the `bitcoin.address.toOutputScript(t.address).length + 3` is not applied and there are no problems regarding change addresses formats.

Similarly as you, my code chooses coinselect/split when no value is set in the target.

coinselect/split will compute a fee of:
      fee: 112,
But the final signed tx size is 113 vbytes (built with bitcoinjs-lib).

In any case this is the fixture for my test in case you want to include it in your set of tests. I believe it will also fail:

```
{
      description: 'Send to Legacy address from 1 Segwit output - regtest',
      network: networks.regtest,
      mnemonic:
        'pulp ritual farm danger swarm topple foil zone limb mail smoke lawsuit rent jungle grain step giraffe inmate outer embrace please lift powder trigger',
      targets: [
        {
          //value: , //No value set, send it all
          address: 'n4dMV2h2VxxrQvh4hpcarSgtJ5azGV6iPE'
        }
      ],
      feeRate: 1,
      //changeAddress: '', //won't be used
      utxos: [
        {
          tx:
            '02000000000101b28e4e4676ab43d55e3d65f118642afab78f2eea3a46e0a9c2bfb32738f9c1d40000000000feffffff02e354814a0000000016001401bd43e70dc8e4fa1dfc465180a61b965026ae1c10270000000000001600140c87dd0cc9f687748c956f60d1eba97c67bcf12c024730440220117d399583cc714c55921ac15f8d7d7f71a124b92e36f3fd3ec0c3d81a66546902204368f40185009a475e9fa2edd434201af983d05182c9f553c7eae95b4ffea6a1012103e35032031e82bebd4b737761537968c69e96bb73819975869b0f23efb5fe249db0010000',
          n: 1,
          derivationPath: "84'/1'/0'/0/5"
        }
      ]
    }
```

Perhaps @junderw can take a look to this?

**Comment by tadeubas** [comment]
On the issue https://github.com/BlueWallet/BlueWallet/issues/4902#issuecomment-1364553585 I've described a workaround to customize every single sat in BW
