### ISSUE TITLE
App Lock Not Consistently Operating

### ISSUE THREAD

**Issue by dav1dpgit** [BlueWallet/BlueWallet#4503]
BW app in IOS does not sleep/lock after departing the app from a transaction details screen

I’ve noticed the app requires a password to re-enter BW if one leaves the app from the top level (wallet summary or all wallet summary) after some short period of time. However, BW did not require a password to re-enter after a long period of time away if I left BW from the transactions details screen.

I would think you would like these to be consistent.

**Comment by Overtorment** [comment]
there is no sleep/lock in bw at all. every time you see a password to re-enter bluewallet means operating system decided to completely terminate the app (likely due to RAM shortage), and thus you need to unencrypt storage when you switch to (or re-run) bw.

if you have faceid/biometrics enabled, you should see faceid requested every time you return to bw
