### ISSUE TITLE
Failed to import: BIP32 Seed/Root Key, BIP44/49/84/141 Keys

### ISSUE THREAD

**Issue by jpthor** [BlueWallet/BlueWallet#457]
Tested many different Seed/Key import options, using this tool:

https://iancoleman.io/bip39/

Fails to import:
- BIP39 Seed
- BIP32 Root Key
- BIP32 Extended Private (xprv)
- BIP32 Extended Public (xpub)
- BIP44 Extended Private (yprv)
- BIP44 Extended Public (ypub)
- BIP49 Extended Private (yprv)
- BIP49 Extended Public (ypub)
- BIP84 Extended Private (zprv)
- BIP84 Extended Public (zpub)
- BIP141 Extended Private (yprv)
- BIP141 Extended Public (ypub)

Fails with "BAD WIF"

Tested on:
- iPhone
- Android

**Comment by jpthor** [comment]
Minor issue related here:

on Fail with "BAD WIF", the app freezes and requires a force-restart

**Comment by thestick613** [comment]
bump for importing electrum's zpub

**Comment by Overtorment** [comment]
Watch-only HD wallets will arrive in the next build, merged here https://github.com/BlueWallet/BlueWallet/pull/479

Will be possible to import xpub (bip44), ypub (bip49), zpub (bip84)

**Comment by crashdoc** [comment]
Any word on importing electrum's zprv private keys?

**Comment by ncoelho** [comment]
Almost all mentioned formats are supported, closing this issue for now.

**Comment by skechboy** [comment]
This issue is still persistent for prv keys, tested on BlueWallet v6.0.5 for Android. 

Steps to reproduce:

1. Generate random mnemonic, as @jpthor suggested on https://iancoleman.io/bip39/ 
2. Import BIP49 or BIP84 account Extended Private Key 

At this point fail alert is shown, and the wallet is not imported. 

Importing Account Extended Public Key to create watch-only HD wallets works just fine.

**Comment by compatibilizer** [comment]
Still persistent. Results in staying locked out of account under certain circumstances.

To reproduce :

- Generate random mnemonic on https://iancoleman.io/bip39/ **with an optional BIP39 passphrase**
- Import watch-only wallet using Account Extended Public Key (xpub/ypub/zpub)
- Receive funds in the addresses generated by this watch-only wallet
- When you want to sweep this account, you can't do it using Bluewallet!

Why:
Importing the wallet using seed mnemonic results in a different root since BIP39 optional passphrase is not supported. This could be circumvented if we could import using account extended private keys (xprv/yprv/zprv) but they're not recognized as valid inputs.

Solution alternatives:

a) Query optional BIP39 passphrase during seed mnemonic import
b) Using a menu item in advanced settings, allow modifying the account root with the optional passphrase
c) Allow importing a wallet using extended private keys (xprv/yprv/zprv)

**Comment by Overtorment** [comment]
related https://github.com/BlueWallet/BlueWallet/issues/3197
