### ISSUE TITLE
Invalid LNDHub URI in latest release

### ISSUE THREAD

**Issue by djschnei21** [BlueWallet/BlueWallet#4852]
Please provide:

* your phone model and OS version: Android 12 on an S21 Ultra
* BlueWallet app version: 6.3.1
* self-test: FAILED "ErrorL Linking can not open https url"
* userId:ea6a742dbce449c4

On the latest release, connecting to my LNDHub fails unless I use the tor address.  Local http or tailscale http no longer work and return "Invalid LNDHub URI" when entered.  Tailscale is my preferred method for performance.  Worked fine on previous release.

**Comment by Overtorment** [comment]
recently there was a change in policy (not by us), and unencrypted traffic (http uris) became forbidden.
we can add exceptions to those rules (like we did for *.onion uris). what uri are you using?

**Comment by djschnei21** [comment]
trying to use my http://100.x.y.z:3008 private tailscale IP.  Tailscale is a private VPN tunnel, would the exception apply there as well?

**Comment by Overtorment** [comment]
https://tailscale.com/kb/1015/100.x-addresses/

hmm, not sure if its possible to whitelist wildcard addresses like 100.*

**Comment by atec145** [comment]
I'm not shure if this is the right place to put, if not please delete.
Since the last update to 6.3.1 (and perhaps 6.3.0 but not testable because of the tor bug) the lndHub URI scanned by QR seems to be different from the shown text Node URI. Wallets created with the (QR scanned) LNDHub would not work.
Before 6.3.0 it worked as expected.

My environment:
LNDHub on Citadel Version 0.5.24
Android 11 / Bluewallet 6.3.1

**Comment by Overtorment** [comment]
fixed in https://github.com/BlueWallet/BlueWallet/pull/4854

**Comment by Funman2** [comment]
How do i implement this on android? Tor is so slow...
