### ISSUE TITLE
App will not open on Mac desktop.How do I get to my Bit Coin?

### ISSUE THREAD

**Issue by SamFraz** [BlueWallet/BlueWallet#5527]
## Are you reporting a bug?

Please provide:

* your phone model and OS version
* BlueWallet app version (settings->about->scroll down)
* self-test passes? Open settings->about->scroll down, tap "Run self-test"
* unique ID for our crash reporting service (settings->about->scroll down, tap "copy")

## Proposing a feature?

Go right ahead

**Comment by niko-underwood** [comment]
@SamFraz - You should be able to download a previous stable version from https://github.com/BlueWallet/BlueWallet/releases until a patch has been released to resolve the latest version crashing on Mac OS. You can also load your seed into another wallet to view and spend your Bitcoin if needed.

**Comment by niko-underwood** [comment]
This issue has been resolved for me by updating OS X to Ventura 13.3.1

**Comment by wayovermyhead** [comment]
Is this issue dead?  I'm hoping it will be corrected in a future update.  Any chance of that happening?  I emailed support and received no response.  Is anybody listening?

**Comment by Overtorment** [comment]
try updating your macos.
also, you can take your mnemonic seed and import it in any other software (like electrum desktop)

**Comment by wayovermyhead** [comment]
> try updating your macos.
> also, you can take your mnemonic seed and import it in any other software (like electrum desktop)

Thank you for your response.  I think the answer to my question is:  Subsequent to recent updates released in May 2023, Bluewallet is no longer compatible with Mac OS 10 (Catalina).  This is a permanent change.

My computer is not compatible with OS updates beyond Catalina.  Due to these circumstances, my only alternative is to take my seed and move to another wallet.

**Comment by Dantesic** [comment]
Hello. I have the same problem. Unofrtunately I lost my seed for this wallet so I went to transfer the funds to a new wallet. But now can't open the app. It says "BlueWallet quit unexpectedly". What should I do? I upgraded my OS to the latest version . macOS Sonoma 14.3.1.

**Comment by wayovermyhead** [comment]
> Hello. I have the same problem. I went to transfer the funds to a new wallet. But now can't open the app. It says "BlueWallet quit unexpectedly". What should I do? I upgraded my OS to the latest version . macOS Sonoma 14.3.1.
> 
> UPDATE: I managed to enter my Blue Wallet. The problem was that I didn't have the latest version of BlueWallet. I went to App Store and updated my Blue Wallet. Then I entered it without a problem.

Hi Dan, I am very happy to hear that you were able to open your wallet again.  I was never able to upgrade my operating system due to the age of my Mac.  I was never able to reopen my wallet.  Bluewallet left me there with no warning and no solution.  I had to use my seed to get my coin.  Be careful out there.
