### ISSUE TITLE
Fee Model heavily Malfunctioning

### ISSUE THREAD

**Issue by Brhel54** [BlueWallet/BlueWallet#5611]
## Are you reporting a bug?

Please provide:

* your phone model and OS version
* BlueWallet app version (settings->about->scroll down)
* self-test passes? Open settings->about->scroll down, tap "Run self-test"
* unique ID for our crash reporting service (settings->about->scroll down, tap "copy")

## Proposing a feature?

Go right ahead

**Comment by blankscreengithub** [comment]
I agree. The code is using electrum for fee estimation. It should use mempool.space fee estimation instead.

**Comment by Overtorment** [comment]
i was able to track down incorrect fees to a 3rd party public electrum server (that BW randomly uses), and submitted a ticket here:
https://github.com/cculianu/Fulcrum/issues/197

and i added a remediation for BW here: https://github.com/BlueWallet/BlueWallet/pull/5704

**Comment by cculianu** [comment]
I am not sure this issue is related to Fulcrum itself. I did upgrade Fulcrum's code to more closely match ElectrumX, however the issue as it appears cannot happen according to my reading of the old or new Fulcrum code to build fee histograms.

I do believe that is may be a possibility that the public server is griefing its users by returning bogus data intentionally, since I cannot see how Fulcrum could ever generate such results.

I am making a new release of Fulcrum now to use the latest fee histogram code imported from ElectrumX, so maybe maybe if there was some subtle bug, it's now fixed. 

But I am skeptical of that -- I think it may be possible the public server is griefing its users with these histograms.

**Comment by Brhel54** [comment]
Thank you for your interest and the supporting information provided Intentionally or unintentionally there is obviously no chance to recover my losses If you’d think there is I would appreciate your suggestions on how to proceed Best regards Am 29.09.2023 um 11:30 schrieb Calin Culianu ***@***.***>:﻿
I am not sure this issue is related to Fulcrum itself. I did upgrade Fulcrum's code to more closely match ElectrumX, however the issue as it appears cannot happen according to my reading of the old or new Fulcrum code to build fee histograms.
I do believe that is may be a possibility that the public server is griefing its users by returning bogus data intentionally, since I cannot see how Fulcrum could ever generate such results.
I am making a new release of Fulcrum now to use the latest fee histogram code imported from ElectrumX, so maybe maybe if there was some subtle bug, it's now fixed.
But I am skeptical of that -- I think it may be possible the public server is griefing its users with these histograms.
