### ISSUE TITLE
Improve backup importance

### ISSUE THREAD

**Issue by ncoelho** [BlueWallet/BlueWallet#61]
Make it very clear to users how important it is to backup their wallets.  Some wallets have constant reminders/warnings until the wallet is backed up.

**Comment by pajasevi** [comment]
This should be a part of better onboarding after the app is first launched. User should choose if he's normal/advanced and then create new wallet or restore from backup (plus maybe mandatory password/PIN). If new wallet is created, user should be required to backup and validate backup in order to use the app.

**Comment by Overtorment** [comment]
After wallet is created BW asks to write down mnemonic.
