### ISSUE TITLE
LNBits LNDhub API unexpected response: {"detail":"Not Found"}

### ISSUE THREAD

**Issue by 20a8vnf30** [BlueWallet/BlueWallet#6953]
Bluewallet 7.0.0 encounters an LNDhub API failure with error: 
API unexpected response: {"detail":"Not Found"}

I just updated from Bluewallet version 6.3.2 which did not have this issue.
Samsung Galaxy S22+ with Android 14, One UI 6.1

Bluewallet self-test OK.

Serverside is LNBits 0.12.10 with LNDhub extension version 0.4.2. 
When refreshing Bluewallet the LNBits logs displays:
"GET /lndhub/ext//balance HTTP/1.0" 404

When refreshing the same LNDhub account in Zeus (where it works correctly) the LNBits log displays:
"POST /lndhub/ext/auth?type=auth HTTP/1.0" 200
"GET /lndhub/ext/balance HTTP/1.0" 200

Edit:
Same problem and error on iPhone XS max, Bluewallet version 7.0.0.

**Comment by vicariousdrama** [comment]
I confirm same issue. Started failing ever since 7.0.0.

I can workaround this temporarily by importing the wallet again performing these steps

1. Begin Add Wallet
2. Choose Lightning
3. Click Import Wallet at bottom of screen
4. On Import screen, click Scan or Import a file at bottom
5. Scan the QR code from LNBits
6. Discovery parsing will show the error `API unexpected response: {"detail":"Not Found"}`
7. Click OK
8. Click Back
9. On the Import screen, the URL scanned from the QR code is displayed.  Edit the value removing the last trailing slash.
10. Then click Import and the wallet will load.

**Comment by vicariousdrama** [comment]
Since this started in 7.0.0, that was the removal of Frisbee in the module here
https://github.com/BlueWallet/BlueWallet/commit/411284527dfdd0a13302b2030b6669f55cc04d0b?diff=unified&w=0#diff-b1d18cebc95f998bd03564e1a1a8f497ef6648da6fde40b0046e0b8cf5e6a032R251

Frisbee was leveraging URL (url-parse), and my guess is that library may be sanely reducing multiple path separators to singular format. (e.g. // becomes /). That would have masked the issue until now when the urls being fetched are simply concatenated to the baseURI.

Recommend a tweak to mitigate here in BlueWallet, but it's also technically a server implementation bug in LNBits or the LNDHub extension as servers should ideally correct for this.

**Comment by conradotorquato** [comment]
Awesome. I was trying to find a workaround for weeks. Thanks!
