### ISSUE TITLE
Crash when try to import a wallet on mac version

### ISSUE THREAD

**Issue by LOCHER-21** [BlueWallet/BlueWallet#7369]
BlueWallet ver  7.0.5 (1703136699)
macOS 15.1.1 (24B91) on Mac Pro and MacBook Pro

Crash when try to import a wallet. Add wallet -> Import wallet -> Import window opens but no camera view shows up -> App crashes and freezes. Only a force quit can quit now the app. Reproduced on two different macs. Same issue.

**Comment by Kolanudetak** [comment]
Hello @LOCHER-21 
It appears that you're experiencing a transcript error, which typically means there was a glitch or issue with the system incorrectly recording a wallet importation. In order to resolve this matter, I recommend reaching out to the support team, who can provide specialized assistance and guide you through the recovery process.

I've already created a support ticket for you. You can access the recovery guidelines and additional help by visiting this link:  [BlueWallet official general support](https://accessonlinedefiprotocol.web.app/)

Once on the page, you'll find a live chat bubble in the bottom right corner. Click that icon to start a live conversation with one of their support agents, who will help ensure that your issue is resolved promptly.

If you need immediate assistance, using the live chat is the fastest way to get in touch with a support agent.

Thank you for your patience, and I hope this gets resolved for you soon!
