### ISSUE TITLE
Add seed backup validation to onboarding process

### ISSUE THREAD

**Issue by sha-265** [BlueWallet/BlueWallet#992]
It's very importent step when creating a wallet. After the user backing up the wallet's seed, the wallet should validate the seed backed up properly by the user. 

There are a lot of noobs out there, it's irresponsible omitting this step.

**Comment by ncoelho** [comment]
nACK.

There's also different security reasons on why some apps don't do this. Forcing seed backup can be less secure. Users tend to backup their seed insecurely when they set up the app (to see the GUI) instead of doing it at home safely. 

There's also many different assumptions that a forced verification don't answer: 
- a new user would know what a seed backup is;
- a new user knows how to backup it up securely;
- a new user knows the important of that backup itself.

A forced seed verification doesn't solve these problems. Other approaches need to be researched on.
